# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Module with precomputed constants for detecting LCGs."""

import enum

from typing import Any
from paranoid_crypto import paranoid_pb2


class LcgName(enum.Enum):
  GMP = enum.auto()
  JAVA_UTIL_RANDOM = enum.auto()


# A list of pairs (c, d), such that
# c * k - d is close to a multiple of the curve order if k was
# generated by the random number generator.
ConstantList = list[tuple[int, int]]

# Python 3.7 will allow more precise definition using TypedDict:
#
# class LcgConstants(TypedDict, complete=False):
#   curve: paranoid_pb2.CurveType  # The curve
#   lcg: LcgName  # The LCG
#   lcg_size: int  # The size of the LCG in bits
#   lcg_output_size: int  # The number of output bits of the LCG
#   sample_size: int  # The number of samples needed to detect the LCG.
#   # The minimal number of signatures needed to detect the LCG.
#   # Detection with this number of signatures may be unstable in the
#   # sense that only a small fraction of cases are found.
#   min_signatures: int
#   # The number of signatures used in a sliding approach.
#   # This number is chosen, such that it is both small and gives
#   # stable results.
#   sliding_window_size: int
#   bias: int  # An approximation of the bias of the constant list
#   # The parameter w passed to HiddenNumberProblem. This parameter is
#   # determined experimentally. Typically it should be larger than
#   # 2 ** bias. 2**32 or 2**64 are common choices.
#   w: int
#   # If True then the constants can be used to detect LCGs with signatures
#   # where s was replaced by min(s, n-s). This typically happens with
#   # signatures using secp256k1 to avoid signature malleability.
#   normalized: bool
#   # A version to keep track of the generator that has been used. Version 1
#   # uses LLL to select a set of constants where the values c have no linear
#   # relation with small coefficients.
#   version: int
#   # A list of pairs (c, d) allowing to detect the LCG.
#   constants: ConstantList
LcgConstants = dict[str, Any]

SECP256R1_GMP32 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        32,
    'lcg_output_size':
        16,
    'sample_size':
        24,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        14,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x50003fffcfffe000400050000fffdffffb085d8fea7f824203d258150d49b,
         0x65ee9493b395b3e9a615f2e56f2b8b4940e2ed8aaeba5f28b033b6d5079e67ac),
        (0x1000000010001fffdfffe000100040001bce0faab20ef0dad7a565b4f,
         0xca6d306a7445d946fd36002bd616c171ac2414645d37e3ea839666a30e6c88c),
        (0xfffdffff00030003fffbfffd00020002bcea80deb1b70d3ce816bd85,
         0xc00226f98f0ea677ad5e66cc8b964b4acc27050e294978c01bbb43cf74045761),
        (0x1fffbfffe00060002fff800010005fffd79ca01c263791a771fa495b13649,
         0xfffd70da56b2f360227b1f7fcbfbf90e2fd0371a3c7ac6f84ffd4da9a2316938),
        (0x1000000000000fffefffcfffe0006ffffbcdffaa964055619d8969bdefe92,
         0x26b2e25c5af6524a665262660f2aa821197f72c7679f56d01ae0428d1ffd1802),
        (0x300020001fff9fffd00090005fff8fffe36b469d49b2b1b86b409,
         0x8ca637b054ac4d76214c9d6cf07aa6e6849ecfd135ae3fb2845b90d5171cfd17),
        (0x30000fffdfffbffff000300070000ffff36afacecace246a4fa0750531edd,
         0xa5f0677f27fdd4cfc6a83286b7cd8f9e8c527467f34c71f856ec4960dee60ff2),
        (0x3fffffffd000000030003fffe00000000f39ceab3594974c27601bd2c9944,
         0xf29877140d1f1146f73f2f86e625e6562f5442a895b60f27e255b870c6c85264),
        (0xffff00010000000000040004fff9fffcbce63dcb263e2fe065955b48,
         0x594dfea4b1844bd3bfeb7e35fde1bf264433dd66ed901168c61d30629e5bd54e),
        (0x4fffdfff8ffff0005fffffffafffc0000b0866b90d4479e5b8a7d2475,
         0x5a0ca0d7e7d9c8a0a486852c1064033b84426b83b8e22d18ebf7798dab08bbad),
        (0xffff0001fffefffe00000001fffefffdbce43dc5e31e6da65528a77e1825,
         0x26b32f52e2c72e2daee32e79cea2224f114f979e3720368ea60dad3fe1740b5a),
        (0x10000fffcffff0004fffdfffe0005fffcbcddb79c2800503ebdda4018b7a6,
         0xd9483ce5a84573cd96cd03b310d5e6e5ad7a4e92d8cddbde280802385f3c8f7d),
        (0x10000fffbfffe00000002fffffffdfffebce9b7946b1298aeaeac0e0aeedc,
         0xcca388506008a61889708f28ab47c98993cbdbb5a702deac064588147cb33221),
        (0x10000fffd00020003fffefffa00010007bcebb78c27f286f9f1032e502653,
         0xd949b123c5502c998cfb07c10c91a2bbed64d289a0c3905d400680ae70250cf0),
    ]
}

SECP256R1_GMP40 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        40,
    'lcg_output_size':
        20,
    'sample_size':
        20,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        17,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x500009ffb03ff6064fbfb9f9f6405055f50cdb667fec6f1e50a3f0d0d16e,
         0xe9da941247fd1067c9b33e5fa33cd654887c78f6137caa256862f0fb5a0ae192),
        (0x9ffff6ff611009029eef86fdfa106fd1dd21ef382245586d55e312f2c579,
         0x34ed2caf90a1249afd8b9a7a4c08524bd9458e6f7491b5d4626971181766384e),
        (0x3ffffeffbfd0010540306efb03cf9074eb3f2e7ea6d2ce19b5a86259bc15,
         0x48a2b220ee3df43579982f5a24b24614b22ef6118dc932158318f69285a6938a),
        (0xdffffeff20200110dfe0fef00a1f004fbb431b5b85399027f25061318ca4,
         0x628dd865de107810bb0f42f4e3621f279261b329bf62740b030dbce46f39804a),
        (0x1400003febf6ffbf7408fb409f9704f55b22568ec76e8f7385c53a11f944e,
         0xd817a18f95af1b4e06f768ca2cc3c9bc5814b744de992022d33954fc12c74f8),
        (0x10000dffeeeff20711103df8fcefcf06fdd19cff6a6b449f7c492513bc36,
         0xf4ee115f95bb7581249040e10bd9d4476fd68a95c7745237c5ccd5fa3dcb9546),
        (0x1100009fef00ff5ff0ff0ba01f90f505dbfbb1758d04aa9c51017ecf32682,
         0xbd90ffa6917c520e18693d3d21fd76f92be761a529ff807e219214bb9f66eeba),
        (0xb0000bff4faff3f3b04f6c0cffb0a0a2d1db2882d6b85954f5ac2e9,
         0xbd91cf1ca694c77d13110ce2ea64fd18110e0616950cab5101c8ff8fd55dca39),
        (0x2fffffffd03000012fcf1fff0030e090f3676e6fbf4ae3987b1655d60410,
         0xb130e4037a88d4c1e781bdcc47184640a8d256c144979d4a1cf02686e5800f7),
        (0x6ffff8ff909007036f6fc8fd05903052ddb0df316d0de504fe6a92eac8f1,
         0xd9ea16c2e3949a5529bd73218a226d656ddc5276e2531df8ca3ab8f6df1a7a32),
        (0x8fffffff701ffffe8fdfd00205202f1dd556bde192dff22ac5346f33bff6,
         0xa9dac7b942d7a8d080b90cd02f7e50d7dc227948c7f41f404ba3c14f5c93ea76),
        (0x100001ffeffffdfc0ffee2040901204bf2d14ed40162d4883a1108527b6e,
         0x58939b8290cc6ee605ad7eddc60a9bfd49891bad7d1aca4c6198f074e05b7683),
    ]
}

SECP256R1_GMP64 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        64,
    'lcg_output_size':
        32,
    'sample_size':
        15,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        22,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x23afffffd7e00000277fffffc27000003da57311c6b4d9f1005e6d47f57,
         0x1c72a1ca6f036741376230c055c7e4d724ffd0441ea829bca2fbe3eb347ef53b),
        (0x3ccfffff9310000079c0000004dfffffc3af9e6cb03e6077e1c09139a2a,
         0x4b01631172336f7cb002d9046ad14815e48ad28d69396ce824e24be8dd805ae4),
        (0x7affffffdf0000014efffffc35000006c7c2fa702cb18d49ddb10de4f6,
         0xae68d8b59e418e5a344d89d24c19c827444ebe2864ad5e302911328ff72601ab),
        (0x156fffffe230000016a0000033dfffffe2c1979ddeeffbe333d3bcf0ee3,
         0x896ee62a911d7ac245ed580556f8b93b740b25b8dea2c0d9a3a546a4762bfabf),
        (0x386fffffd0900000384fffffbfc0000079052be3124a63d2c6079c270da,
         0x236770526102d8b8e5f9aba874d61b707a36265180db5cec3d1de3f283765d63),
        (0x113fffffc9e00000341fffffc87fffffec5a9064290c921294d0effeac2,
         0x4a659982f4277a13479f30e82233cede0db0fa6001cdfa7c17efa6b89d6dff8d),
        (0x316fffffb12000001f400000438fffff6b2adb092b7bd0398165f16af4f,
         0xb70a9d4bd10e10fe0723c7405c10161dcefada2bcb201daeda35f3f61f35c63c),
        (0x544fffffc0f0000045effffff97ffffffa66d26f69e623b3e3868a7b2e2,
         0xff23c9461fed9306977e2cf92f4f4c0a01c0bed4d6c7b7fe6e02ae01cda1027d),
        (0x3ab000000f9ffffff7100000371ffffffa2e3397aab406cb42affb8c5ca,
         0x83db3f69ee66814f843b9521891732624dd3314e9af4702d173858df0e3b93fe),
        (0x11efffffd9b00000566fffff8c90000046ec6f3069bc55778f0a3f47659,
         0x7891a8ade0c9bca5660660acc176956bfc03da1fc7a096f60865582f7e3dd81b),
    ]
}

SECP256R1_GMP128 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        128,
    'lcg_output_size':
        64,
    'sample_size':
        12,
    'min_signatures':
        3,
    'sliding_window_size':
        3,
    'bias':
        27,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x4b088666fcf77998f4a6b827d661ce3f24af75fa42ec07381c0e34f360,
         0x9c6088c21714af4b263aad1959c3f4988a4d43838bbe17b96d3d7d0243b073b1),
        (0x1d4371ac2dbc8e53b9f0b3f70152bdb56f21f2d9266ef381a912982507,
         0x522bfcd5815149e9a954a756256813f5da6d99d879da2a090ea5987bf0efbe5b),
        (0x19aa3b418955c4be9cf7c8e3e9b2725db33a56d4dfae2883d28b1e036b,
         0xce7a12cbca1028a04204629404ceeb4686ad22337055ded8a8601baee1ac8eca),
        (0x1259f81c0ea607e3cfd12cb9e888cb6237175256a924b6b5bb90910376,
         0x8263b850dec933d47a8250a7fa3430109459e02ad9f8af16d1383f1fcf332c7),
        (0x3a45529e8ebaad61b8946c8a3fb0e614c87112573b6d45c62fac783a33,
         0xb5215a6578f88c28f248fa9fd166cbe9cacc29723dd1bdc9e3f42892f0041bfe),
        (0x4040622a35bf9dd5ad4922fbb1f73f2e7f8dfb7ce1c1638d99f0e8ffba,
         0x49c4c3ca4ef5b91a394f19a4d8b5b5df2b973942af9fd8728113ce6f20eed853),
    ]
}

SECP256R1_GMP196 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        196,
    'lcg_output_size':
        98,
    'sample_size':
        20,
    'min_signatures':
        5,
    'sliding_window_size':
        5,
    'bias':
        16,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x9beac7904fb495c58ca26a3af3cb3c4e0ca65224fb9a88b4073ddece0dbf,
         0xd60915c49ed739d2e8d951e919ba8f47f490085c084d58249ec820b5caee931a),
        (0x117d1e699fa44bf16d8d940ea92bc3fe2369b0ea2ab666a0d6a5909ee38b5,
         0x6b42e972c2a5ae3526fb29305d7bd807e66d56609620741c9c2200301bc7c5a),
        (0x132fceaf331ae91a37d10ae5d6876e1916c9e60c55dadc32f2c91cc7287d7,
         0xd0bba76712397045e60900a169a370feea3449cd27a6b274b6e2a5919f33a664),
        (0xa0e881a856321019ab732fe7369092ea64e41ce75e1297df35a38d0b17d4,
         0x9423d15148a51857bcc57a2165fa1150d74c44306465d56eb9752dc4b73f64fb),
        (0x96ed0d7849371b716dd1a48eb105e5b1b468876299227988d8d8309103aa,
         0x17ee5a38f5095b4d14ed29b0cd7b0d3f54ecd1da051d3c55906148e3e23a9be8),
        (0x2515ea98c2e06c829c9f93c3a5bf91ab8f873dc8f0c0f24c7bbd13766e,
         0xe2c437687e58db26e8428507826dd4775d9e6a44c153bc7f7b7306baee6d9cb3),
    ]
}

SECP256R1_GMP200 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        200,
    'lcg_output_size':
        100,
    'sample_size':
        24,
    'min_signatures':
        5,  # 5 signatures have a 50% chance to find the key
    'sliding_window_size':
        6,  # 6 signatures are typically sufficient to find the key
    'bias':
        14,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x1fdaf45d2f75fb5db16f94a2648fcdf6f9c93aa8785530b393470aab86f0,
         0xfd9d48a17cd92f7bae8e5ca06fd5f47b1a1eae9c3e6128b875ace717946ce636),
        (0x1006144eeddcf325edf433da21bc144c7e315d2bceae8ceca0e0d57aa3f12,
         0x1ea3da0e90d1ec13e4adcd13bfd5e641c8908cfd25c52492cfb255fcb7ecd8cc),
        (0x20ec4500b7812a3d6e8334c2ae73547f03abab00387fd951d58f67e574dad,
         0xd5a2d33f1d638d53fe6ec7f4f15addaf80f6c513f7bf6035009de22a1f6565e9),
        (0xbdca197b6123d6393480e0c78ac79d609bd908aaaeac86c790e38c6a29366,
         0xb9d3b593eee79988c91b0b5303afa6dac9469d6f95838f6bd9366fdc357766df),
        (0x9dbdf0dd8569efed58987913474f74c79f764e53114f6cee4f21e174e1542,
         0x7c8c0176cd43c160ffbf712b8403da573825837549f9464639d1c3e2c59db547),
        (0xc1c57807071295a4eaaed35bd759971f7b122fffbdb72cde034c6dbf9a146,
         0xb50e46d8e899f87e2637c493e35b8fd183b6054cc416a3d2dd1ca885658ae8ab),
    ]
}

SECP256R1_JAVA_UTIL_RANDOM = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256R1,
    'lcg':
        LcgName.JAVA_UTIL_RANDOM,
    'lcg_size':
        48,
    'lcg_output_size':
        32,
    'sample_size':
        120,
    'min_signatures':
        2,  # 2 signatures have a 70-80% chance to find the key
    'sliding_window_size':  # 2 signatures are used here, since more than 2
        # signatures do not significantly increase the chance to find the key.
    2,
    'bias':
        5,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x1000000010001fffefffe0003010400ffbbe4faae22e90cb0364457,
         0xd2029019e6791a64e78743fb66036ddded9674f099b255897ec97b9da97a9fcb),
        (0x10000000000010001ffff00fe00feff01bbe7fcac64fb5516104b077805a340,
         0xf34601aaa42eb20c109b8d8832089305c0f235e6bd0187d036d9112f1cd30099),
        (0xff01fffeffff0101ff03fe0200030300bc2a8982ee12adc29e,
         0xa0dbfe6bafc5abf484e13b35e613b7cac3a7835a572da5120777380d9617b943),
        (0xfefffefefd00fd00fefdfefefd03fd02bb2511f30e86f74b,
         0xd8b473588b7b541a1bb0f97fb43dd6c080fcc6e10f2eb741adda8f7b5b8d54a6),
        (0x50105fffffeff01040105ff0600040102b14338cb80b5b06f022808e6979fde,
         0xb19e15c4ddecf09a89811e27ca23ff3dd4fe2b3ba3f8b3f9310e0de35909f453),
        (0x1000100010000fe02000302030001fdffbce5b7981a99b54d4088d20d8e,
         0xfbaa3020a49297dd3ca89d6dccb3ea689a4ddc8ec16bbfc95e65f9f04d2f8865),
        (0x2801280000fe02ff2c022b0229ff2bfe2282f7975836def11adbce2f2d30711b,
         0xb5c68c2bd0ecf70c8bcd5daea3bec1ccd954a47c52855266000a36cd0ef97488),
        (0x460045ff0101020245fe44fe4602470134a65d3319b8f4ea32b8124f645c8ce5,
         0xc310d0170259f0f3634cc43842409c036b00153deb980f047f4bcdb6aa17cbc3),
        (0x1c011cff01fe00011c031eff1ffe1f0018aa18b97f955c8bd17c67913fd36d86,
         0xfe7f86cf2f21b5d229631b82570d968777cc3d7e7845d43b9d738c65bd6e7fb8),
        (0x2ff02ff0101020103fe04fe040101000135fd400a434ca5cb4eb3e540f7442c,
         0xa31a3c0462d0b7398b2015e84832db96a42e640dbe9779b681295052a8497b37),
        (0x1000000fe03000100ff0001fe05fe0401bde9fa67d25e08ea7fc126d86e94,
         0xe74e26c8c4b0f8a83b76be2de654ea456be2d4b0b73205aab2a42d80f6fcff1b),
        (0x100fffffefe00ff0300fefffe00ffffffbaa1dfa755ff8b515ac976,
         0xcccb450cc090ae0d048879081f4e2bffc5ddc33a1c4fce37220e865f986698ec),
        (0xc000bffffffffff0c000d020d000bfe09dadd9b00701be09b6510d92a28c2ea,
         0x4b86a2d9c81d5081b8b5d31b23f774d224e26df9b1a517fbbb75e0856adaf531),
        (0x7000700020003000b000b010a0008ff0a2a5e061d0f8d187042165d3aa11cbd,
         0xdd3ace982729db72ddca4f8c5b25b3283ee349d45608e2a0ff3d782900bdfd1c),
        (0x4ff0500010000ff0300050207fe06ff02b1c9aff0e6e5ab3a80e533edbfc5b2,
         0x73ffe00358f4c9505dc46f2bac47725e74a1b7f1b8f9647a63e6446c63671589),
        (0x1ff00ffff02010001fdffffff00feffff7911cb4357d426f808058c579c1d21,
         0xd9b94b0f4326301194b92cff709abd9da1ff74d858c151031a2b6ebf1691ae6f),
        (0x60005ffff02000107ff05ff0700090105706f4d8477a3c132ff5f862108ef54,
         0x3581e74ad34bc136031c413944210e09b08b12c6a37aac3fe4e1587cfe101c70),
        (0x1a001b000101000018ff1aff1c011b00152f8c631553e3fab967e41fe06362a2,
         0x55438bf57718d00f52e06f68f1f077b1bee044d9e751841a115d4a5e5f7ac0ab),
        (0xff00ff00fefffffe01000003fe030000bd2ad0dd877a63e93e5a8d4fc5a463,
         0x37429dbde0a78cb65b4940ccf02f30bc2482d9534cfce4de5593d09778195db5),
        (0x1ff03ff02010001040006ff05000601077a17014797e8f47bb9392c888c10d7,
         0x504452d95644e2ed6abed9f4e45418d034381b45c2d0b5023da752a9749060f1),
        (0x440044fffefffd01430044ff43004201312d8a7e9061b8739d6edb1fead904a1,
         0x39ab7336abcee86a1758fcc19cd1f35326b8649ad8d7677fafca55f4e931f145),
        (0x190018ffff00fe00180018ff17fe180011759dec927eb72c5c1e25f60d56c604,
         0x125c61f995a7fbbbcebc95347e479cd090618a246dc86c2282ec06cbfb5de1dc),
        (0x3f004000000000003f013f003cfe3fff318007eca7443fb14ae5f4b2cce6cba5,
         0x77b0fb4b42f7f0b915fff46c0359e58cf990b319c4cf2f3eb31fd43940e91622),
        (0x6010600fffefffe06020702060006ff066d2d3438cdb2b5b65adb9b155fa9f1,
         0x2dff3e04317924dac2d1caa9ceb7a8fbc54f7c3161ffc1a6278707b981c80fad),
        (0x2020100fefd000001040001ffff0000007b4983f44a4d935b855446e4e9ab,
         0xa910d992131ff458dc5d4e1a8da5ae681f6239f85a1e115f08a13d429c02b357),
        (0x2a002800ffff00ff29002802290027001cfd03a46e7a4046c3fb4809a0517693,
         0x8e5c74790cbb46f83f9b70dbdd9a4a54f3e4ec5f0313ae2b58ddbccadfe1743f),
        (0xfffffffdfefefe00fefffefffefefefeb8e4f6ade675fc7d16f48a77,
         0xf039364228012af1e20474732dc3ccf2e40abd5a7ed50a996d812daa7bbb703),
        (0x680067fefffefeff690069ff680167004dbc2392f38f908b47100470219b8ce6,
         0xad012f352f6d75d04313ef94950551e318c748fcee09b136ce692a91fdd71260),
        (0x3ff02ffff0201010400040105ff050000f5e03b751438221cd150f89df2068c,
         0xa290595704b68694dfc21fda76a451ac36b4dc1f706c460ce1c5ebdc9b94d893),
        (0x78ff77fe0001020177ff76ff790077ff5649c9223d49784ebfe27dfce723041a,
         0xe897199f0ad361c5334b1d47d071cb74ba349877bddf52ec41f5cca1b64293bf),
        (0x1010100010003000401020002ff050104bea99e93c7f92d31ae06e634b3cd7c,
         0x69bc8e469a360d49e9750daa90567397737aa97046ae29ca6978708a67a3005f),
        (0x23ff23ff000100012500250024fe25fe1c92d7ec49bbb6d4c5fe39c32118364c,
         0x910b2ff37ada81fd2b646b3b652dcc9299cd3516b98572701bafe56d4dc42814),
        (0x2dff2bfefe00fe012d012d002bfe29fe1ff3e49d4f00468289ff9e5fbdc5a22a,
         0x3efa192b0c4e6a4b6c9129edb41ec15094904874fd65d453856af27defbc1e4e),
        (0x210022ff04000201230022ff21ff23ff1e5ae12454354c224c284c7c26ea434d,
         0x8fa194ce0fdc81350f6c0fc4ebc7d7e17658e976e0367a2e6e6ec857087c10a1),
        (0x7ffe7fff0001ff007dfd7fff80017d005b7163fafd1530ff6cf723f119bab9d9,
         0x25a5a8c0ef4125309934410d2d5ffa3326e0b0b743b455cbf84f68fc17052e82),
        (0x2020300fffdfdff030306010301000102794bf8c6fa51c27a65db18039f8ad1,
         0x4f6f7331ef33c103eb7932cbf719ceda2745208762a02b9adebd1f2627dd1ad4),
        (0x200030002000101030003ff060204010277d42c1833d61063e19bcab90c5373,
         0x3d0275cc76b19e1caf2fb12597ba87431f06d1d040d134bb777f4d9d8ff1d809),
        (0x420043ff00fffd01410043fe4200410130b2bdcd9533e2242eef9d0358040010,
         0x4da9ced5705d89e55018dd68d0d64546635af90d6a5dfb6b07e43b659ecca018),
        (0xff00fefe01ff00fffdfdfdfe01fefffbbc24d0d74ff46ca18368cc,
         0xa7b210854c293909f63d10759b7e3d6aed965c69240667c44327c3aefc817e68),
        (0xfefffdfeff000102ff01fcfdfffeff02ba2b13392d035ae47391cae7bf93,
         0x58884507569c041f8580b0c4920fd664d2ef2a464ae4eb3766a92c57eecf1c61),
        (0x1ff01ffff00ff0000000201040001fdff7911892f54cd2b358428b1bebe52c2,
         0x381862c55cbae33d6ee47499bdf476559b9bbf0cd2aca946675916eb4010bbd1),
        (0x350034fefefeff01370135ff32fe33ff281bf8022ff5331d2036abf4aef10f50,
         0xfffe8788e1b152780e8d5ffb49b65fceedc05056536026801e5baf7e6603f02f),
        (0x440045010200000041ff450047004401302b8b7f50826a4900e4d8bac90f133f,
         0x273f6c9a52f82bf438ce4d7e917491c7d6644853c5d3835cc32f20b826a089d5),
        (0x270125fefefdff012602240023ff24fe1ac70525147bb1f901bfceea2a4ce2ea,
         0x8c45eb2916cee84aca303213df0f20d2dd9fea63e1ba9ffb3314f58b22e8476d),
        (0x2000101000000ff0301000000000102027acfaf01a9a802f218932d9f151c54,
         0x2f062c769341750213e749d8941a3d3dbe41e213d61f42762e51706844cb9a6a),
        (0x31003000000002ff32ff31003402350026275d66b72375488e0910de9eeef2b0,
         0x4476ca575151502612d03466d54d8520034595d3d8235a623d80a7edc2609a3d),
        (0x80107fffefefdff06010600070006ff01e6f4a3a0e7238bf2502e187f3d76cb,
         0x9aa18b54aade0fae6cebe4b099266f92a232ca4cd7332093b92231e06a9aefe7),
        (0x1010001ff0200020004000402030004fdc2a3e52328eacb569450,
         0xd81f22d2702871cc40c293880221cd6c7078e8f3a5cf4a15d4417d32f595d958),
        (0x390139fffffdff0039023aff37fd36002712528521b91a34d61c481ff25c14a6,
         0x578e6532406cc306463b0388c9b4d50c82c76287c4fff0c5f921050962eb0ff7),
        (0xd000f0100fefefe0d010e020d010dff0a95c5cc226947a83a5cad6e4d4277e7,
         0x429444ebfa81150d9d11c4b66ef0d489917a10cd43c139dc9493121b78b39818),
        (0x2010000fdfdfeff0101ff00ff000000fe7787da10e515616d1bc89d103c8f0e,
         0xb310a82f850dc83a5e84b42cae282e1382dbf204b98de958cce763de35dd96a7),
        (0x1010000fcfffcff01010000feffff00fdbd9ee063c1a91eb684a8a9b6eea2c1,
         0xd1360a3a696b0e6b1da7718b4b77641bbfccc914ee682f6882fa7c3e42daba81),
        (0x9010900fefffe0007ff08ff0a03080102a1e059fb2c8f1d42927f599488cb54,
         0xd59c4328984ed21740889818cd97ad9f8d33ae3ea2376e873c9237fd6b204dd),
        (0x61006000000000fe60ff6002610261004790cacfb0e5df4b5adc17e52f15daab,
         0x81b73373b0dbc7f5f6f9d14ff502b12ed180f99683deb95284daf63f538cbc59),
        (0x1f001efffefefdfe1e011e001cfd1cff15e20c3912b84c4e1b99ae2cfa23d3d8,
         0xa5a8013afeea055907225e36a94afebb015773950a7fa6fc40f247746a4b2912),
        (0x10002ff03000101010001ff01ff030004bdea31aaa2c5c479315f57e1f35b49,
         0xeef27593a37a5ed5a57b1c498b587b863ff05835f230c856ecd0e289b982cce8),
        (0x30100ffffff00ff00010001040003fe01377194e8d3520362035046cb3a136b,
         0xd38e92d6fabd88245c8c422ff4eda56e1549203a7f59ecbc9bea768d81befc49),
        (0x1bff1bfeff0201021efe1dff1cff1dff16aa9d2fa4082493241d3e420905e568,
         0xf7cb65f0aa29653ca66361c508e6d2827f3d95dded87d6f81d06d3eb179363a9),
        (0x7b007b01fdfffdfd7b007a03770076ff58c254333dd14194624c29d0ea753c15,
         0x1991d85595b9f1e1a478458c051b6902c09f8bbb620bd2979b4b9b318f6067ae),
        (0xfdfffdfefefefdffff00fefffbfefcffbb6a293a7ca0a3325ca4dcdb,
         0xcd732a0b13c4764f99f1a8bca1993889a9fc37f316837fc4b7275210c73df170),
        (0x200020000ff00ff02020202010000ff0179d1702a7b81ca3fac9d96,
         0x5459d88dbcc2006239095b9674ddf7f31f425ad453cd060825b7c9d462029cf8),
        (0x101020103fe03fe0302040303ff02ff05bdaa5b35dfdd1e13888ef18aa5547c,
         0xa77ee2cceb458c571a2873e5b2f5179b5810321be38dab67a941cf80ee2a789b),
        (0x3101320001000100320032ff340033ff242816c87d831a8dbd0480ca9fc902a9,
         0x912bed3d066faa9e1dd55449bb94d9fc49da5fad719fa0e190b6c7c1ed525c69),
        (0x100fffffffcfefe0000020000fffefeffbba3e0a8102b2477fd9ffbf0,
         0xee523cc1f3e5583862f8492fb2be5b79f347ad663c3d44b4c8b57a0de3af11c1),
    ]
}

SECP256K1_JAVA_UTIL_RANDOM = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP256K1,
    'lcg':
        LcgName.JAVA_UTIL_RANDOM,
    'lcg_size':
        48,
    'lcg_output_size':
        32,
    'sample_size':
        120,
    'min_signatures':
        2,  # 2 signatures have a 70-80% chance to find the key
    'sliding_window_size':
        2,  # using more than 2 signatures does not increase detection rates.
    'bias':
        5,
    'w':
        2**8,
    'normalized':
        True,
    'version':
        1,
    'constants': [
        (0x100000100ffff010000ffff00fdfffafeb7aed89f17d6a8de896c2410,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x7cff7cff7cff7d007bfe7cfe7c007dfede2986554d0414f85c5e0c1c2d257f7e,
         0x0),
        (0xe0010ff110010ff120013ff12ff140003358f7a7df708919898652d28b1bffb,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0xff0300030003000303030202010201ffb8f25c158f582c35348e8b, 0x0),
        (0x800090006ff060004ff05ff04ff07fffed674775a586ee5f95911ea87440123,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x160117001600160115ff14fe14011400fa09ba705fdaa7d2d6e4678842f818f4,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x31ff32ff31fe31ff33fe35fe35ff35fff57560a74221404588b1a194b68e83f6,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x1401140214ff15ff150114ff160016fffd956184fd88b2c8ac6364cd82998086,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x25ff24ff24ff23ff21ff20001dfe1cfeebb72717d9590e6f57ba555154d0772d,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x100020001ff03ff050003fe0300050001bcaf5344deb6f4bae350eb43bcdadd,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x10000000101020000ff00fffffefefffdbaacdce168a8a453cd818eaab3, 0x0),
        (0x100fffeffff0100010002010301030103ba6f8d10e7690d0864e0aeda35e531,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0xff0100fffffefefdfffe00ff00fffeffbaf4e774545d332c69d0be5b64, 0x0),
        (0x3000301040003ff0301030105010601012f0cc47c3d2835db19746298747d7b,
         0x0),
        (0xeff0eff0f01120111010f000e010d00f8f27d35248f2837cee2c9e8c81370c7,
         0x0),
        (0x3c003c003cff3d003dff3d003dff3cfff1c0ee87fd57f513b83a7114cf03be19,
         0x0),
        (0x40004000300040102fe02fe03020200fceab95f5462c7c039e51e6a906a0895,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x260026ff2800270028002802290128fff7b5ed3c20275d8ae9cd7f6f6807f009,
         0x0),
        (0x45ff45ff47ff45004500450046ff49fef10c06c43c40c950fa007921e5e11b77,
         0x0),
        (0x66ff670066006500670067ff64ff64fee11c814e31e2ea606b841c1d67264b12,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x14001400140113ff12fe13fe16011601fd93a5d6ab8913be278a21974c3e843e,
         0x0),
        (0x1b001a0018ff18ff15001500150016fff3b065410c2763d3a9eda578123d355a,
         0x0),
        (0x3a003c003f013e013e013e013fff3ffff74a92cc2f6c3aa3386ffbd59012d805,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0xa010b010aff0bfe0c010d020bfe0bfeff4a8b5519f30d8b874394849efa6f43,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x100ffff01fe02ff020002ff0400040101b96b8d075f008d92a158b6a85c,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x30002ff02ff0400040103000501060002300cc70626feda6d5ac2c6121d3627,
         0x0),
        (0x1100100011000f010efe0eff0f000efefa6499573cd8dc32cff7b599bacf4c2d,
         0x0),
        (0x7cff7c007c007a007c017d007e007dfede28869a5b1b1ad1ada2533eafbdb1d0,
         0x0),
        (0x5b0059fe5a0059ff5a015801580157fee45c0f28eb3b9213272b6c231568854d,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0xff02000300020003000100ff01ff01ffbcf1a564b172c13dbc419b3b5cd981, 0x0),
        (0x140013011301130110ff10ff120114fffc96a71bb99f5b5c708e7354d9981909,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x5fff60ff5efe60ff610060ff61005effe302b7e50e2266aae51f66edf2d74ab2,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x7cff7cff7eff7f007e007dff7eff7dffdd268354467a6d2781e93b8c23cfa10a,
         0x0),
        (0x2010000fefffd00fcfffdfefefefefffa74146760386d618e3dd4f7, 0x0),
        (0x1010000000000ff00fe020001ff040003b96d8bc893fba4d3e6daf013c8,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x17ff17ff19001a0018ff18ff1aff1afef981a08962c8eccc5a46c75dfbd1767a,
         0x0),
        (0x6cfe6dfe6eff700070ff70ff70006fffe47ce1e90f52eaef90a58daf7789900d,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x7ff060004ff05ff0700070005fe05fffbd5b9976e66a6d7eca342d398603c5a,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0xff01ff01ff00fefffeff000001ff01fdbbf1a4a9492b9560221c25f9038235,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x900070006ff06ff06fe08fe0aff08fffc9025dee54fe9e4957f15cf416e884e,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x10001ff0000fffffdfffe00fe00ff00febbad5388b7f2c5fd25fdb9a4158ea8,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0xfff10ff1100100010000f0010ff0ffdfaad2e86696fe6cf7938e6eecdf8305a,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x70006010601060205000501070007ffff19c9692305169bda7ab737454d0c8a,
         0x0),
        (0x1000100000002ff050106010601060101bbaf98968c2d81d0ed02a3b357, 0x0),
        (0x101020002010300040001fe02fe030201bb69ff20c2dbe02202b8340103,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x50105ff07ff07ff070008000801080102a52561bba762ace459551ae50640fd,
         0x0),
        (0x3aff3c003bfe3c003c003d003dfe3dfef30581fa390896e36f55603fd1954dc6,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x10000f010eff0e000bff0dff0f0010fffdabecbd64856ea6e6ddecf47dca8d49,
         0x0),
        (0x3bff3c003aff3bfe3d003e0240003dfef1c331d820f9ea5729aa8d0f6eacf039,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x5d015e015dff5dff5f005e005e015d00e6cf26787eed03bae635595f862ce872,
         0x0),
        (0xfffffefefefefffefffcfffcfefcfffbbaaadc284600711a47a57cb5ed44a0, 0x0),
        (0x2800280026ff26fe25ff25fe26012500f12a45af4f593fd719d03099e063e53c,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x3e003d003b023c013aff3bfe3d003d00ed3645fb77183c984f53b714b4da4914,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x7dff7dff7eff7efe80ff80ff81fe81fde3e238ebe505a478981ce7f70d5b591d,
         0x0),
        (0x470046004600450245004500460046feebc66c50b70cf611062b7f6415a1e7aa,
         0x0),
        (0x6b006b0068ff69fe680066ff680068ffe205f95a6729a976f114bfc39e01f73d,
         0x0),
        (0x77ff78fe7afe7aff7b007aff79ff78ffe0821b1c530417579a693c463d24738b,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x5a005a0059ff58fe59ff57ff58015801e4a25e4b78ea46d7018cf0013deb54f5,
         0x0),
        (0xe000e010fff11ff13001301130011ff02359347e806a381084c944a4f105c2d,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x3010201040104010501060004000300012dcab8a946a97b826dbd7643fcc3d9,
         0x0),
        (0x1010100fffdfefe000001010000fffffcb969442f254667f4db6ed9, 0x0),
        (0x60ff60005fff60ff60ff630063ff65ffeabd7006075c170d501edf7689ca30e0,
         0x0),
        (0x10000ff00fe01fffffdfdfefffefffeffbaac99d89a885d5cb4af7d56b0693b,
         0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0),
        (0x11ff10ff120112001001120010ff0ffffa208b3f3586dd0f110905d23e5409e4,
         0x0),
    ]
}

SECP384R1_GMP32 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        32,
    'lcg_output_size':
        16,
    'sample_size':
        36,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        15,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x1000100010000fffe00010000000200030001fffeffff,
         0x194b4420a7fbc9c0cd25caacf209c40f83881c010fae1126499e73bc432b4f877ff29366932737346c17faaa3ae3aade
        ),
        (0xffff0000fffeffffffff00000000000000010000fffefffec762861c6e17bfc4d0f027db17b6202b528efa91,
         0xda0f1ad52d9739d16d1db0740a747c916e36181f9ba3104bddd2702282523b156a5dac097f4712eaad31a40002e482a5
        ),
        (0x1000000000000ffffffffffffffff000000010000fffffffec7624d81f435f542a59d01ea768f3830ad1a35465b49,
         0x4000403e423b1d8432744e4940fda5289d1785b59574da1c270a37e6dbbbf5970df001590b644de142ce1098cf7ea444
        ),
        (0x2ffff000100020001ffffffffffff0000ffff0000fffdffff562b2122568671aef872824e68a7,
         0x994a720aa9ad7760de6cefdedc66789a0ccdaaa485615d05fb94d99dcea4b5dc236177b4fec69d38b440b1a2ef159909
        ),
        (0x1000100020000ffff00010001000100000001000000000001c76414e3d080847df4862fa455243ee74af5d1de,
         0x994b57b672145d54e9db1de4127cce946db78697197e463a0196a251dfe6419fdd5fe5db3e52d38bda55f547506a446e
        ),
        (0x100000000ffffffff00000001000200000000fffefffffffec7644d81bb9a7b6084ebee0f73f763946cbf90e3aaf7,
         0xffffb7ecae1b562a0f36ffeb713ee806238a09928a711cc9ab35397e34cfd164ad430d00624ac3207c47b870d342bf75
        ),
        (0x20000fffefffd0000fffeffff000000000000fffffffffffe8ec662666e8dac4ac8b8ef1a9cae6dcc458eed51,
         0x8000aa4ca03a7f734cac2ed4c79cc4f0bba7b7763815c577d7c776159a0c7f23482c236cf3a415ec1e04c4be3df6e9d4
        ),
        (0x20000fffefffdfffefffffffffffeffffffff00000000ffff8ec462676e8d73ae87750fadf704e47b77a11d96b301,
         0x26b3ed66b57c3d78e9ff63d2c219d01d250c15bc5c4b660d6b4006ada983058a2441811691e16bf5cc1256f51c42872c
        ),
        (0x200000000000000010000fffffffdffff00000001ffffffff8ec79b03e8705bbd77973048d318e244fd6a62b02ebe,
         0xbffdc944fb842c0cb2c7ce824e26c1b823fa9c24959323a3eb90edf1cef73583f7f270436a126b893a10b50105be04ff
        ),
        (0x100000001fffefffefffffffd00010000000100010000fffec7644d8182fd017f2ba327b880a51bc4895d43f8f0e7,
         0xfffe77c588cdb8f7ae24e86aea32be7010444cc990b3222514f3660ad775bcb3d1a035bd67eb5025d715b78ee9b77918
        ),
        (0x1fffd0000ffffffff0000ffff00000000fffffffffffeffff8ec844d8c74bcc995368bad7524cfb6cd50a7d969b56,
         0x3ffe65a4f84c99a8f6af3caac3c119192f26be4bd71420f137c7a2e927703faf4609ed91b598078ba6089bedb0b0b9ae
        ),
        (0x200000002000100010000ffff00000000fffefffffffdfffe8ec69b027734be26ad87803fe9c99708d2118887bfda,
         0x7ffda29085a9de81c864017fcc6f472807a6f37775a01e07a3bc9ae30d7a94f88dd2e372451570bce804385b8d14df30
        ),
        (0x10000000100020000ffff000000000001000100020000ffffc7644d83bb990a26aeb7aa1da33f9f0942a11cc51425,
         0xe5f1a7ae3fa3825601d761167e8c8a8dbf77953649d45ec85d4a36ff2dc4ac89d36518df27151e7bf33798ba3daf7703
        ),
        (0xfffffffffffffffe000200010001000100010001fffdfffec7634d80f4362ddec9540173c2a94910a192e533ad42,
         0x7fff6389a7eb65df3b95958b34c2db7d6de4372ac383994677cc662e030dd9995a4f6d217073605623d819d1a7c52e2e
        ),
        (0x10002000000000000ffff00000001000000000000ffff0000c763dc4a8f3b164d7b3c44020acb39e6b39d9d132fdb,
         0x8ca58580c6cf9a436c0b827b6fdd2d4be4609cc504e1b747793bb8f68600cc4cb8f8b9af96934c053a85b6d749882c57
        ),
        (0x10000fffefffdfffffffcffff0001000000000000ffffffffc76514e67a5545cdf6bcf955f2a2cf81,
         0x800135210a86e76f0dffd6eb6d04a80bb87f1beaf6aa6253318620b20f483adff426f140a562e65c67d53c51737b2c50
        ),
        (0xffffffff00000001fffe0000ffff00020001ffffffff0000c7624d832cd4e05cf2aaec11056593362e2d40920384,
         0x194bb4425b8faef30fd3ce3dfca682ab0ced544e8a64977597dc0d83bab8257bba4c55e4ee4eee6a2c2bbe981ec520ee
        ),
        (0xfffefffefffffffeffff0001fffe000000010000ffffffffc7638621df51ec256e9f72d22ff13b3ec43059ead965,
         0xf3594e37321b0d380ad13cc6af87cd387a18ba84957823cd982d356de13a42ed786a53ebb2a2ab6b41b871ae0b2fa152
        ),
        (0x100010000fffdfffffffffffffffefffefffdfffffffefffec76314e6091be0d0df2dab3c52c08646accd4bf2c70b,
         0x335a38e6f116d48d831dfc7b251a1ef7645f9412fec1072e38083ba6994d578337d06de7139a2f9887c76141c775bf8a
        ),
        (0x100010001fffefffeffff00000000fffe00000001fffefffec76314e3d07df5b75983b86e970058c350d8,
         0xfffe8a253894ffa6caf03dfb4c0efbfd1a658d72aa4733e577e18a0e89180a663e3aa8aa721d1c9518dce166a7131702
        ),
    ]
}

SECP384R1_GMP40 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        40,
    'lcg_output_size':
        20,
    'sample_size':
        27,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        18,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x1000010000200002ffffdffffdffffe000020000000002fffc76349c8289f13b3017f6c26ded448537ff02d8762d,
         0xe9dafabf08955df4bac2275645e38660a1ff122a4d7ab68e8859e194e96e9ee9251073e48c97201b13915052e188ebd7
        ),
        (0x4000000000100002ffffefffffffffbffffd0000200000fff1b8d3637d0a51ac054fb2ff17f215e832fd0c5366d2,
         0xe9dad529f3cb1708c99e317c814df55c02d1cc4123cd28ae51b1df8f3a254bfb2044d5f23103eac2d8c2baf2d06cfd1c
        ),
        (0x2fffffffffeffffcffffe00002ffffbfffff0000100001fff5529e845dcda265b23bbdcc48a9ff9810472148b20f,
         0x613772ffc17206f64eda3bca8ade80664999482ea8c4d5630944832ef6cc5932e838e5f84bb0eeb7f60dbf98108b65a1
        ),
        (0x200002000030000100001ffffefffff00000ffffc00001fff90c694305176c42a620114d7533077f5606c8f25c4d,
         0x9ec876ff8576d8bf227fd995b4716c3cc292341451a6af883abf90186991daf981e63c78d2cf8e6f982aa6bbb984ef1f
        ),
        (0x5fffff0000000000000010000300001ffffe00000ffffeffeb153d4b58470f3f8cdbe230f563d5aa2d55cb1e47bc,
         0x5ec86329c41b79ce2036b9e47eb6e1894efcb64908f2f40814b7a9d8dd4d415d5787017a5a2cfbe61631305953e5a7fa
        ),
        (0x4ffffdfffff00002ffffcffffe00003000030000200001ffee1f08abd5b9e437dd371567e331b3523c,
         0x9ec8a29adc13c32b73860e79036e5d638b348d51184c2157f028e54d33fd0b9b5e16fe74a23ab1adb87a00f194e15201
        ),
        (0x100001000030000200001000000000200002fffff00003fffc5634a08286477040d3e235f5bcbc9df05ef0f1a504,
         0xb4eda3c8b34e3f98fb1cdb9681288859d6e4f7a6b2a1fa363b22b185290beebd97898be85578bd066e0fd4ed3e8c0113
        ),
        (0x3fffff00001fffffffffeffffffffffffff9ffffe00004fff198d39a19b935ed50172e83ff2e5b944e,
         0xb12b569126619ea4735169a01cc9e235918c83cd3977404c20c82f516a87e50bfad48fe97717659f1bf99ac8c64dc30
        ),
        (0x1000010000100002fffffffffdffffeffffcfffffffffbfffca634a1828d2b0659f8abfbf9a1016818cc520,
         0x9625164f7f79dae119aeedd2a4124128014e57c5665a75813b1c56e87c55d603b111bd3a2287d9471d4568aade7679e4
        ),
        (0x10000100001ffffcffffdffffe000010000400001ffffefffc7634a08289f13c8ac425e6b49a313eba00c1cf2012,
         0xf4ed7346581774b9cf8e21c305718391578719c2af05d8bbad9ff008f8ad6d66a46b0d3afc6e1f4932815d470600c622
        ),
        (0xffffd00001ffffefffffffffe0000100002ffffeffffcfffcc6357ff553a96b3cd33be69e8702618d531b2,
         0xc000015e87c075ab93caacf5d09f27858e61744c6325c91b69af71b0d07c1e9fa3a7cdbc2b73e82cd30afeade1060c96
        ),
        (0x3ffffcffffdffffe00001ffffeffffe0000400002ffffffff1e8d408532c4931f377bca709928f44ea24893e7529,
         0x13b5e55a1007a37da5192f9feb9aa49d0f89aa4afd0962e758b0d211a5913bf667fbc2dc3244514ca81801237827b6c4
        ),
        (0x3ffffdffffd00000ffffc0000100001ffffefffffffffdfff1d8d3ceb67d34f0a8b0565ce4cf5482d37ec7165242,
         0x34ed61e67997cbfc84a603feb2e41ef284f2860d0bf5d4d5dd54a79f4c6952dee0e5ec5e4fa2823b9d8311de814d700a
        ),
        (0x400000ffffdffffb0000000001ffffeffffeffffeffffcfff1c8d322e0629103780558452acaba27cacaf19075cf,
         0x1624d4202857d97f6ca7a2a59986d8aad72d4fb569615c3ddff962193ea920c303209c7717efebd3e9d3613d40b26973
        ),
        (0xffffcfffff000030000100001fffffffffeffffcffffefffc86357df55e76cbd202a47c0975e17940c88856675a,
         0x56252b20882120f40607ab4230c5350e65bc5e4209d3f3d11c204e68d2f40fb91543cc356c4a963710f8a8a2c41d9963
        ),
    ]
}

SECP384R1_GMP56 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        56,
    'lcg_output_size':
        28,
    'sample_size':
        21,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        24,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x11ffffffeffffff4ffffffd000000f000000bffffffafffffbf4fb7328b5ac6623aa0d76b29d45b3be30e3a1e4f,
         0x37970ed051b0f3b5a06719b3b89290cf51e8f8361e0b51537ebea6de552709997f94e73afadc8d042066f3f2f62237a4
        ),
        (0x11ffffffdffffff6000000b000000efffffea0000026fffffdd4fb73223f778d0bc9e7f32836a55da208599690e,
         0xdaa048f29a9a44af16c1e20112849eed3ceb92abf5dd3a0cf76139100b5b0f93998c32e17f3da19c20237678589e6998
        ),
        (0x3200000040000004fffffeffffffe3fffffedfffffddfffff4b16523508b9a55313365fe09ff6d4c394cadf3287,
         0x39ed8cab30f3e8c29bcbdb93abcc11e5e4ee5e8226d1ffc0b04ae8e3de09a61d257e17e233445f16e1a2c048e35454e6
        ),
        (0x1afffffe5000001a000000f0000011ffffff20000000fffffaf7792d384a3f05724380eaa3b1f925fe269541cb9,
         0x27f06c91e1aca17161a50cc25485ee41b060fe97978109c03270d4513da35062fd3ff09e7ef0b95a019fe8a315d72f64
        ),
        (0x8ffffffafffffdc00000080000018ffffff20000006fffffbe27db9bb46e86bf3d0c5b5d2ea5816061bf78aab0,
         0x73db199ef455b1143b0fb24d0c37eb932a3da59349d1afc31b475eca19618f3d24ab6295da1f2739b35aa5306201ed3f
        ),
        (0x4fffffe9fffffdfffffff7ffffff2ffffff70000008fffffd04f083c49c8957d082f30829bb266b18e5a3b2443,
         0x44acfd6e2ab5b9098606146a4a0a59ca7b793e69fd84d2933d51e2e1df4638aca6548a6cc091f4bab3af351f4e716789
        ),
        (0x6fffffd800000020000000ffffffd00000060000014000000b3b71f1635407c17a55eace25ee99e707f3c4145d,
         0x2f2e1effa27e9b641b3d8cb4c28d594ca049cdcbb76258682e3a5e20912cfcabe8b07de84f50cbd86def6083482b6b3a
        ),
        (0x150000017000000c00000160000031ffffff7ffffffafffffabb255b72a7462b79f116fc49bca036b0288b4c23b,
         0xb2ea1359cd39cff895cfc5f388328cd1a3b3e6517bb63bae2864bdd70847c6695949b98cc0311bece5e15c404d1ff59d
        ),
        (0xf00000120000012fffffdc000000fffffff80000010fffff95ed18a619ef2dd85465b903609a88d0848a22e832,
         0x95b91392a3fb363797c65bbc2c9bba6c6f04ba65c7dcf54b63115d50905135d4947416de40608c88783a9ed9bb93ba70
        ),
        (0x37000001800000050000006ffffff000000050000013fffff13655a6958ccf1bcf30e112524ad98831bdcbebe19,
         0x1cf6c4721af45dcf8ed8b3cfeda325bde40f24bbf949fc1c2c98968b12d6231d84275906ce11c7e52da9907821e809ab
        ),
        (0x3ffffff3ffffffc0000006fffffe4ffffff9000001b0000021d8d363c46629888a9cfaab1a46ede33be96b99e6,
         0x197508e6247da04c7afbdc8aba9642ee9dafc79b32fc5a07164e4c4b80772fcd53b1de4a0ad022ba79a59770a4c0d390
        ),
        (0x32000001affffff6fffffe3000000a00000050000006fffff5e16523132a59c068d47af1bcf15f480109a85b3e6,
         0x3c7e41eb2743440bcbc8f4965d7168afc36b12189129465a12e03af094d9a05d26c35b1738c4e9d04f40960f97f7a383
        ),
    ]
}

SECP384R1_GMP64 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        64,
    'lcg_output_size':
        32,
    'sample_size':
        18,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        24,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x4ffffffeeffffffe9ffffffe0fffffff8fffffffa00000024e4f083cc877bbfae5e4f8f656ff408bb343e85d2,
         0x3dc2a75c48f0460a77a0d18691b017eab0cfee32fbe5c833305d219664bdb2e5ff349f1425091803c3f4993a66dfa15d
        ),
        (0x7500000015ffffffe30000001dffffff94ffffffbbffffffdd20626c28bfc0a025aa666be17e5c9b92d4187029,
         0xd01b8634d5d2042dc3b31e3d33ac9cd6bf5e363258dad7c055de24867d1082889d4d7a87d6036acaaa57d22de3180190
        ),
        (0x580000003d0000000c0000001c00000028ffffffffffffffe38a22a4a675a13d21d2c245e03c61766f8969b74b,
         0x856250fd67a7197a9f10e41afd7dd2761c6a2fb37242f6039098724fcabf3614871dabf5d59ada16b9b833ce37f81f46
        ),
        (0x7bffffffc80000000300000029fffffff5fffffff2ffffffed94198b16ad01440b96b6820e82ce61e52b3255be,
         0x571053a9df75a16cc941e00d46bdd10600681a5d9e5dcd8086cb6d0029194bfdcababa74df94a26b23a786e43f7fdd8b
        ),
        (0x4ffffffb40000008300000042ffffffeb000000040000001ee4f083789398e29d3ff14fae6af0f691b0cb6eb8,
         0x5910e950b1800cd9d53d01abba4db759013402a3e84fefca31dd5da930eb0af595724e0fafd177f2dba4d54c69123fb1
        ),
        (0x32ffffffd7ffffffce0000002500000011ffffff75ffffffb5b8c871187f7a073a732c6c16d5b277a3f34d4d08,
         0xb947f5ec64e16ec483b98f6076b6915ec3c551db5dbdb11dcb5df90ec4ac5a15b7bb1d1d86e11fb7251f9ccbf8319f4d
        ),
        (0x40ffffffc9000000010000000b00000043000000200000000fa036adcb2bacfedfae25ec540cbd17a48f74c829,
         0x2073cfba21435e25da82405aab9f801ebf1f534cc3555436ddb99842e87abdd24e3315515e572dc16d5b09d75b0dc676
        ),
        (0x48ffffffad0000003900000036ffffff99ffffffcfffffffdbdb511a4efe89f39156a64a21608c2f01a223f8bf,
         0x7ada71afbf9de94e96ef74cb5c9c9f816cbed757ee8539c9e2485f2e1092a94c1fcaefb12a4570116c4255105809c069
        ),
        (0x860000001800000024000000120000000200000034ffffffe75dfa926a863146d80cc65e9daba6d93ef276c357,
         0x3dff6a636a34c017751779ede24740e7b2d30b6585beb90043995196bf490991bed8782cd5d51ebcd8d818bcfe48aa3d
        ),
        (0xb7000000130000002cffffffd6000000300000001ffffffff687fc679a5fd08b7d272cd1f4b79f15c990080393,
         0x97bb30149963873d6e819f345f2dc9697f55309263078c066af281629269909c0c0d1cf86a435d5eec0ae6acbe0cb5e0
        ),
    ]
}

SECP384R1_GMP100 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        100,
    'lcg_output_size':
        50,
    'sample_size':
        15,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        33,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x481abffffffffb27d00000000787dc00000001fe7cffffffef88d56ce603ca94c46bbc93c819771d37d4677a,
         0x8d73fbdd274ec15bd43ff02cb86728d7f92e5355cf8f423c272acbb78a5c280d9cb91b0a878acea7b1d02d61807934a8
        ),
        (0x40f7c00000001c405000000001852c000000014d3efffffff17818babf91ddb8c9b8a60f0638a5a953c74e2b,
         0xab0533a2c3bd3b3c1d212a635ec26982e2fed2aad59588af88b64202e4d168d546f9bb2db11b010f8bd7795dbc586854
        ),
        (0xba447fffffffc3148ffffffff69de7ffffffff968effffffd68d87a2a8b5fd94a1f7f37b3cd591b3e2429169,
         0xb4bf0338401de8aa35c92784b41b4ebd3ba7f9c2d0e22517be126eabbd558309aa99bb8b00f7c068f8f273f30cb429c3
        ),
        (0xe2a8000000000c0ef0000000016834000000010fabffffffce4233d796e0f811cd663e6826ea78bf04fb445a,
         0xa86713be45ab4b4c1c8769c62620fc8e9a2a9d99b264e56b17d52b2f9d5424b026bf6e5104e0d5e9d2c116a0f2334ce9
        ),
        (0x122ba4000000033102ffffffff83430000000019872ffffffc0380c0c5a7263c2dfb3b6c70e6ee505f9bed4f7,
         0xfdedce8273b4b53eebcb03c7c548bdf0dc812687604aa17ce5ed4d54ed643bde331e079aef35e7e5277a60c0c9f85ebe
        ),
        (0x53dd7fffffffe89fe00000000395cc00000002ad09ffffffedc1aa8cb21eb697952f059ede2f78523bec7914,
         0x54d74cad7480d61f2f6d2951e25b8638e9d28f8ff8a65351a7de7e8144cf2517474773db022f90777e7be7b198307a23
        ),
        (0x102a83ffffffff81baffffffffebdf4000000044e53ffffffc6abece0a8c85f5fc6d54b498e4a8a22d71caaee,
         0x64ea617079c937db65a2ade8584fa36874f42fb8ec58097991c7ac0fa514c7d9fa99d88c9844d62be3ed10aecbbe1842
        ),
        (0x9873c000000014628fffffffffbd9bfffffffe0c07ffffffdec565ab7482eacd29253c5672b5a4d75552e949,
         0xdfd7d36d3cd536b68ef41a9591a5b7181fc82d2029ac80057dfdd5bde2be71eadf4f10de4e73914b110969d586f0a1d3
        ),
        (0xc50f3fffffffe362f000000009c91ffffffffac765ffffffd476044f5eec490054a317d69283017b91b7b518,
         0x90aa996f343aa4361b6fc22f284ff9e7d2825ef80635c87a0bc1ea198ef81dfd35cf46617b170ec7941994a4e7dbd136
        ),
        (0x10f8b800000002cd14ffffffff58b5ffffffffd7f5fffffffc358ea694dd6f3adb3cbbbfcad1c910b5493f803,
         0x3164531cb0948c867de56ea255e27567958f8701f15334b58b7404264795071acf553191fcfdc26c21d3503d16054033
        ),
    ]
}

SECP384R1_GMP128 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        128,
    'lcg_output_size':
        64,
    'sample_size':
        12,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        37,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x8bc7ae900000000038fd750fffffffffd7408baffffffffff21efe3c7628b9e3a806f3689680f74070f66e2,
         0x454988fdaa053bf355f416ba20ed704f82981b0995ce59063dbac0d4e56ebb3956d873026f8159e4daa7d8b656f29124
        ),
        (0x83bdb3ffffffffff38cffefffffffff71434590000000002db58c42b8b68e8ec1d4d458ab8f13a4b354138,
         0xa8aa037cd589f760061a7cc52d51d4d9d9013cccd31dd9a2be83e974216c331641e47c212f644ec9ddd509a136d60ef2
        ),
        (0x52bb237fffffffffd893709ffffffffff585d98fffffffffa4f366538366965db0c8c663fcd9d0591c9e3e1,
         0x7609c88d09f707b3718f84f94c30b0bd92b1db6a6f51eb6b0be2ce1f99829a9d55e7bab6c17a0d9526ecaab772cd46e9
        ),
        (0x2543df5fffffffffa74d2210000000003db3fc30000000008c0cc36b5710288a1246279fde8d5ed26a6ec42,
         0x2fb03da61eea5834c75513d0d923407b6472f49bdde91cd00db32b4abf4305b87ed1617e0d05c300155d7ee6c566309d
        ),
        (0x64f022600000000068a63480000000001a81c5f00000000013c7a3a562c2d4d16bab056fe5ffe48bbf575fe,
         0x3759197473029ce95fb24981c2f0f9ab7454c6ccfcbe04a3be033afbd81f3651fd253f6976b071b64a35c03d735e6da3
        ),
        (0x3f0840affffffffff82f85800000000050bd39bfffffffff7882b37f4ecefc692b716e3bd6f11d0839d144b,
         0x54fa24bcc80f0cc921f3cc8dbc0523d5bf932d9f532b81fa00dd1fea3bf563c06d2e4ba43ec5b89fd917e332733cfdfc
        ),
        (0x1025a00ffffffffffe6c91d00000000085922c6000000000267e837cd9b1cf98f26e583fd800026800cfc5d,
         0x31308df23a2b2c2aa48bf30a43a30834dbb621937a5040b861da87a1963c9b6a556e91870fdbfdc1a728c2186e76ae93
        ),
        (0x4101d69fffffffffb11cc04ffffffffff0e8e3a0000000002c2a4baaed5f0a3c9444a7cb52e61a0ed49e2e2,
         0x669908b7b7b394b39e16d88783b472600d2b5a3639da73203803ebefb539800425975714c5d2eaa504af4f0ce628a572
        ),
    ]
}

SECP384R1_GMP156 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        156,
    'lcg_output_size':
        78,
    # TODO(bleichen): This is just a guess. Needs a correct experiment.
    'sample_size':
        12,
    'min_signatures':
        2,
    'sliding_window_size':
        2,
    'bias':
        37,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x1348190b913fffffffffda221e1363fffffffffef9e18c4f47bc6d2495604f0b014295b219c3b0838470fb8,
         0xccd2f8c8368c280e6d50c32afbab40f8eb7797d477a54d285198f2d7ea356062ab253b10959767e83956876e1dce48c3
        ),
        (0x3a5bf92bb98000000000561c3c9f75ffffffffff90a4a11de71828c1e993d5cc47594244da5f983d1c2df1c,
         0xa43720af1580a417d8e4b9a886e2814352a7897745dd9a08f64998bd6d7918fa9e525433f6f1ee0bbebe2596fc123cbc
        ),
        (0x55af9909d4000000000239ae4a068ffffffffffde2ec3f992d0d23c64f31da524c7b2cdf5b77bd78b4a058,
         0x722f7b014798bfbdb95063c97b65d74cc9d55794ea52b7c87a2cd38391dbddb1637533f4d85ed7a64a2877dea242c62
        ),
        (0x169b30e9294000000000ca159d575200000000003b845fa7df0036f8276fe424eadbed337fedc6a41758d7a,
         0x137be1e2fbcfaf25273bd5d48635e3f5c6f3c768a401c8931947dc3435a089421272f90ecf2547815a208652b0a822fb
        ),
        (0x11e72c5695bfffffffff983ad82cbbfffffffffe1e5db1e3fc0a78f27d171fe501d5749f50cc7783146ad9d,
         0xb8705f1a084e75cacf475d0dea2047ddd3923f68f0780f5e3968cbf30abbb2ed4b6b7992cccde576e5d164194fb6ded1
        ),
        (0x362d368b8d000000000008ae92b550000000000409ed4f0f9404f2be1f70dcc8d6f7a2aadbb4b6d62a3238c,
         0x291ec35b43b7611e217a3205ca18764058502bcbd95925a6e7dcc3eb8c4c13447fa36cd9204b4b6e8db8d331dedf136c
        ),
        (0x1d0675e658bfffffffff433bad9c3900000000028edd0296a994d208fbaa876d6d5bd8fc3f2503c88b9c388,
         0x176a9c8c86d5812747a1f876a2d6197a0ffa7c843420fa7245bef623c5e8cf54c94a2dd4be51983df0191b8e67801262
        ),
        (0x210082c1fa7fffffffff24ef4c55fa00000000019187ec24f0b3b013485475ec92b66ab76be5469fa6e01c5,
         0xa2afa8e6d115adf852d989629017dd3c4b27991fb98e824b5319c771f8cdfba7fc7bf96430e034701367fb7838cd4d1
        ),
    ]
}

SECP384R1_GMP196 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        196,
    'lcg_output_size':
        98,
    'sample_size':
        12,
    'min_signatures':
        2,
    'sliding_window_size':
        3,
    'bias':
        39,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x24da5054b65b0cb000000000006c9e54929b5b4dfffffffff67dcebe512aee0605bdf3f25b80c3ed56ff08b,
         0x2cea2e1c3c50ec61ce2053b46ea7a33b640be963ee904a172595fad128594056680a9bd24f91bf40be854ac7b554dc20
        ),
        (0x529ad632cf530407fffffffffd2ed5abfc0cfb60ffffffffecc2a5a1ead3f6f1339e41304caf11a079ebf96,
         0x1daebc10d23e526e5be8ec12e3d8c0fca3f6f861e06cb33a75b5e814038080d1068b40974a755ac78d6d7e56ab9835c5
        ),
        (0x5d06f23e7c59a27ffffffffff693f53ca8619d1ffffffffffea303653ffc0fdbf22363e246757c3f2b66cd,
         0x1a30c3a9f545f2d0c39c2be0ba81be3ce0cb56ea510b944933c199b9e5ab915ba367252af2289943ba5833809ba3fded
        ),
        (0x150c558461150e78000000001731144244376bbafffffffffdc84842008f7bc2f55c74f035695c4ae4ad7b8,
         0x97f9e99f7ea03bd16503fcc2e43ac31d3c2ffd80e9c8048a68f75cdfcd4f9d3324b48c22d2673d4250a73712d950d19
        ),
        (0x746d7311e09685bfffffffff62dde9d2d8229e10000000001d1358b7053ef1dafeddb78569ad15a092ce66,
         0xab5283fa9b03678890a11dd3f5f139888991c159970dad6c08097c12ac0a56091e1a5fb037cf6e9028c6df5394067a22
        ),
        (0x4b9b0485fed9333942445fe3ffa15073cca344fb4c5f82e9ee6a233baa63beae5ec96a98139eebdd4b213b85f9a35f6,
         0xa324f383b7b52d179b284e968a00ffa79c88e6f713fcb00989c27c782763a5fba6e9d7dd54c2395c9dab10fd7e7dc72b
        ),
        (0x6607cd5eebd49034000000000e382f8896f04c37ffffffffec951b4a133946ecb0c6384d4305b57f9bd8734,
         0xea67ecd0b8f44094332050901842c31256c93f982cac1e332619a01055aa2a9c860d264bb68b96addefcee95f80160a
        ),
        (0x341636b52faa810000000000183473430c4cad36fffffffff45be6c9fdbaa8cb3bf832a46c82c87448f6176,
         0x1c39090c3ef4fd4e20d4679fe269913057039251ac2136169863d6e53f82a8cdf6eebf698a8f99d129378ab84745eb4c
        ),
    ]
}

SECP384R1_GMP200 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        200,
    'lcg_output_size':
        100,
    'sample_size':
        12,
    'min_signatures':
        3,
    'sliding_window_size':
        3,
    'bias':
        39,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x15c47134c342159100000000045aac731d0e149a6ffffffffb3bb88526f6a95d40d00c224e882e12a456dc9,
         0xd13722697c2cdd481ca6fc1f3d5f4b34bc21e736f95536344c7e04910116b59a6bfdfe8c8042852bfe293da88440978a
        ),
        (0x97dc63fee737f9f7fffffffffe780dd25ab73d2d3fffffffde2adece5537fd30fb43b5d11020b633197670d,
         0xc3ed9a90471641946cc8156673cc3268d6af0d6bba1fc5422cd1f5ff7bfe6ea787b993d4e831ab5c18b58138b06ca152
        ),
        (0x5bae0b02a588c311fffffffffc2c4be19c3f0bcf4fffffffec0e267df2ce02691efcd72604e8ef015e13ebd,
         0x8a9192cdd3c3c838e5fd9cdf403b544a8cb9f449262e7aa1c70f0e9dceb9e2b37c2216cf871162010f0ec7d1d05d4a4c
        ),
        (0x79bb323271793c6affffffffffb3a3bcfb54bb34efffffffe4c965b783d39851826ae437d7b37d74723a048,
         0xe9894186c739fc1e716967fdaa37de2ba52a924ce9ff87d28e9c251219347a3b0a9a2849f6723bebd24c723443a9673
        ),
        (0x719eda7cb8b6c290000000000450f966091af1c96fffffffe72f4801eb318eb65d09a5b3555feed3ac5c1c8,
         0xde3a787b7bdb6639535e8c00c2bdb2fd8212572fb28d78f5480cf51dd58c0363ff6257ada95e8007ba2aeb2ef7b28ca5
        ),
        (0x51c66bebb505628a0000000002dc6d528bb87498afffffffed7307d6b7f3c1351fda286257d12384b5c80d7,
         0x882166e7c39495eb52b781a42bcd15d4cce084a9fa3cb8b5b65dbc81b468a89908392b8df6a78e316df0f7eff4761a4f
        ),
        (0x640acb9a58056b0dfffffffff6960983de93792d2fffffffea33e70f9d3bbdeb57059c9ceecdf9ad60f97b9,
         0x6eaf76dc32398cc34f081fa69c04bd9becf47159185911327e793dbb280e541ce73409934f9964726c76443eb84ebda1
        ),
        (0x848b5fb08ae63c7ffffffffff2cab6842079acb2ffffffffd7f86b46a0eec8b229e00ef844260606fcf3c2,
         0xb2cfdee11c82fa40e471fd815d08de637176cda4af1c47a6a4234a263a310b1478bda88d29748b8789c4f47e89270781
        ),
    ]
}

SECP384R1_GMP256 = {
    'curve':
        paranoid_pb2.CurveType.CURVE_SECP384R1,
    'lcg':
        LcgName.GMP,
    'lcg_size':
        256,
    'lcg_output_size':
        128,
    'sample_size':
        15,
    'min_signatures':
        4,
    'sliding_window_size':
        4,
    'bias':
        39,
    'w':
        2**32,
    'normalized':
        False,
    'version':
        1,
    'constants': [
        (0x32d1a6df307df63bccd5720600000000734d1ff0e0a3edb26a7ceec3b1d4b422a88143c83f33060b3548373e,
         0x91017915ee0d1d4ac9cdf70b0d56035c8dbf261bd878b9b18b3198f935fff716762854fb2ff61e719816900e4346d5e6
        ),
        (0x11b369f1232f25b43e75837ccfffffffff3b667f8fb56572b84a3585ba93d79ff539cf4b5105390a4f83e05ec,
         0xb8ebf66046b652875b15d38787b3212abe53f5522ca0c0bb7ea105150aa4f32302bea46d5bb69951caa686a925d44b5c
        ),
        (0x6ffd6743a8b3a6ccc58bb412ffffffff3b70ac9d530698865026291ff0304a1a6fe93a555f9391a8fe10a02c,
         0xd654216221448fda205e01fba0259bc43e2032463ba0d5febc21541e71ad7952bb82700c5bf13820fc5b29252e755dc5
        ),
        (0x5d6d1e67b14c09ed70966a42ffffffffd2c3e88de84568064b47185beae148f00e6958aedcd826a0f24fbe03,
         0x551745cef4620b025fa638fd44c8778afcd8634a5f84b36e11f32fd405bfcd7b54ea3f7afcadf8d2a7ff1b51f0ec2013
        ),
        (0x1afa7287a874b44de460a771000000007234b2dcdf6668ec7eb9281c1c5732d22cc91de894b4d24fd295707f,
         0xfc7f161943029a601143a183956f0a7ef59c39a5b9027d9cb421832d45a610fd2c5dbb4f648298e2680de4f95cb64a83
        ),
        (0x108a656363b8abe649262edfd000000008b09a3e9909526ab7fc44797a3ee78d4f21d130e8d98259cec7d23c3,
         0x37af1acd19d3cdaf9a5e0a892c55fcf17d0c265650849e2ad472e0ca9eb7474b9c2673dbfc735a03764a78d5e84b0daa
        ),
    ]
}

CONSTANT_FACTORY = [
    SECP256R1_GMP32,
    SECP256R1_GMP40,
    SECP256R1_GMP64,
    SECP256R1_GMP128,
    SECP256R1_GMP196,
    SECP256R1_GMP200,
    SECP384R1_GMP32,
    SECP384R1_GMP40,
    SECP384R1_GMP56,
    SECP384R1_GMP64,
    SECP384R1_GMP100,
    SECP384R1_GMP128,
    SECP384R1_GMP156,
    SECP384R1_GMP196,
    SECP384R1_GMP200,
    SECP384R1_GMP256,
    SECP256R1_JAVA_UTIL_RANDOM,
    SECP256K1_JAVA_UTIL_RANDOM,
]
